version: '3.8'
services:
  app:
    build: .
    ports:
      - "80:8000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - CLIENT_URL=${CLIENT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
      - DATABASE_URL=${DATABASE_URL}